
import React, { createContext, useState, useContext, useEffect, ReactNode } from "react";

// Определение типов для перевода
type TranslationKey = string;
type Translation = Record<TranslationKey, string>;
type Language = "ru" | "en";

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  translate: (key: TranslationKey, variables?: Record<string, string | number>) => string;
  availableLanguages: { code: Language; label: string }[];
}

// Русский перевод
const ruTranslations: Translation = {
  // Общие
  app_name: "CaloriX",
  settings: "Настройки",
  save: "Сохранить",
  cancel: "Отмена",
  delete: "Удалить",
  edit: "Редактировать",
  add: "Добавить",
  search: "Поиск",
  loading: "Загрузка...",
  no_results: "Нет результатов",
  profile: "Профиль",
  logout: "Выйти",
  login: "Войти",
  register: "Регистрация",
  welcome: "Добро пожаловать",
  error: "Ошибка",
  success: "Успешно",
  warning: "Предупреждение",
  info: "Информация",
  close: "Закрыть",
  continue: "Продолжить",
  back: "Назад",
  next: "Далее",
  finish: "Завершить",
  yes: "Да",
  no: "Нет",
  all: "Все",
  none: "Ничего",
  or: "или",
  and: "и",
  
  // Авторизация
  email: "Email",
  password: "Пароль",
  confirm_password: "Подтвердите пароль",
  forgot_password: "Забыли пароль?",
  reset_password: "Сбросить пароль",
  name: "Имя",
  surname: "Фамилия",
  username: "Имя пользователя",
  remember_me: "Запомнить меня",
  dont_have_account: "Нет аккаунта?",
  already_have_account: "Уже есть аккаунт?",
  sign_in: "Войти",
  sign_up: "Зарегистрироваться",
  sign_out: "Выйти",
  sign_in_with: "Войти через",
  sign_up_with: "Зарегистрироваться через",
  
  // Навигация
  home: "Главная",
  diary: "Дневник",
  analytics: "Аналитика",
  planner: "Планировщик",
  recipes: "Рецепты",
  progress: "Прогресс",
  community: "Сообщество",
  dashboard: "Панель управления",
  my_account: "Мой аккаунт",
  help: "Помощь",
  about: "О нас",
  contact: "Контакты",
  
  // Дневник питания
  breakfast: "Завтрак",
  lunch: "Обед",
  dinner: "Ужин",
  snack: "Перекус",
  water: "Вода",
  add_food: "Добавить продукт",
  add_meal: "Добавить прием пищи",
  add_water: "Добавить воду",
  remove_water: "Удалить воду",
  today: "Сегодня",
  yesterday: "Вчера",
  tomorrow: "Завтра",
  calories: "Калории",
  protein: "Белки",
  fat: "Жиры",
  carbs: "Углеводы",
  fiber: "Клетчатка",
  sugar: "Сахар",
  sodium: "Натрий",
  cholesterol: "Холестерин",
  vitamins: "Витамины",
  minerals: "Минералы",
  water_goal: "Цель по воде",
  calorie_goal: "Цель по калориям",
  macros_goal: "Цель по макронутриентам",
  remaining: "Осталось",
  consumed: "Потреблено",
  burned: "Сожжено",
  net: "Нетто",
  total: "Всего",
  meal_time: "Время приема пищи",
  meal_name: "Название приема пищи",
  food_name: "Название продукта",
  food_weight: "Вес продукта",
  food_calories: "Калории",
  food_protein: "Белки",
  food_fat: "Жиры",
  food_carbs: "Углеводы",
  add_to_diary: "Добавить в дневник",
  nutrition_facts: "Пищевая ценность",
  serving_size: "Размер порции",
  servings: "Порции",
  grams: "грамм",
  ml: "мл",
  g: "г",
  kcal: "ккал",
  
  // Планировщик
  meal_plan: "План питания",
  weekly_plan: "Еженедельный план",
  shopping_list: "Список покупок",
  add_to_plan: "Добавить в план",
  add_to_shopping_list: "Добавить в список покупок",
  remove_from_plan: "Удалить из плана",
  create_meal_plan: "Создать план питания",
  generate_meal_plan: "Сгенерировать план питания",
  customize_plan: "Настроить план",
  save_plan: "Сохранить план",
  monday: "Понедельник",
  tuesday: "Вторник",
  wednesday: "Среда",
  thursday: "Четверг",
  friday: "Пятница",
  saturday: "Суббота",
  sunday: "Воскресенье",
  week: "Неделя",
  month: "Месяц",
  day: "День",
  
  // Рецепты
  recipe: "Рецепт",
  recipes: "Рецепты",
  ingredients: "Ингредиенты",
  instructions: "Инструкции",
  prep_time: "Время подготовки",
  cook_time: "Время приготовления",
  total_time: "Общее время",
  servings: "Порции",
  difficulty: "Сложность",
  easy: "Легко",
  medium: "Средне",
  hard: "Сложно",
  cuisine: "Кухня",
  category: "Категория",
  tags: "Теги",
  save_recipe: "Сохранить рецепт",
  add_to_favorites: "Добавить в избранное",
  remove_from_favorites: "Удалить из избранного",
  share_recipe: "Поделиться рецептом",
  print_recipe: "Распечатать рецепт",
  search_recipes: "Искать рецепты",
  popular_recipes: "Популярные рецепты",
  favorite_recipes: "Избранные рецепты",
  my_recipes: "Мои рецепты",
  breakfast_recipes: "Рецепты завтраков",
  lunch_recipes: "Рецепты обедов",
  dinner_recipes: "Рецепты ужинов",
  snack_recipes: "Рецепты закусок",
  vegetarian: "Вегетарианские",
  vegan: "Веганские",
  gluten_free: "Без глютена",
  dairy_free: "Без лактозы",
  low_carb: "Низкоуглеводные",
  high_protein: "Высокобелковые",
  low_fat: "Низкожировые",
  low_calorie: "Низкокалорийные",
  keto: "Кето",
  paleo: "Палео",
  quick_meal: "Быстрые блюда",
  one_pot: "В одной посуде",
  meal_prep: "Для готовки впрок",
  family_friendly: "Для всей семьи",
  kid_friendly: "Для детей",
  budget_friendly: "Бюджетные",
  gourmet: "Гурманские",
  seasonal: "Сезонные",
  holidays: "Праздничные",
  recipe_calculator: "Калькулятор рецептов",
  calculate_recipe: "Рассчитать рецепт",
  add_ingredient: "Добавить ингредиент",
  amount: "Количество",
  unit: "Единица измерения",
  all_recipes: "Все рецепты",
  view_recipe: "Смотреть рецепт",
  min: "мин",
  recipe_name: "Название рецепта",
  
  // Профиль и настройки
  account_settings: "Настройки аккаунта",
  personal_info: "Личная информация",
  change_password: "Изменить пароль",
  notification_settings: "Настройки уведомлений",
  privacy_settings: "Настройки приватности",
  app_settings: "Настройки приложения",
  theme: "Тема",
  language: "Язык",
  sync_settings: "Настройки синхронизации",
  data_export: "Экспорт данных",
  data_import: "Импорт данных",
  delete_account: "Удалить аккаунт",
  dark_theme: "Темная тема",
  light_theme: "Светлая тема",
  system_theme: "Системная тема",
  russian: "Русский",
  english: "Английский",
  version: "Версия",
  terms: "Условия использования",
  privacy_policy: "Политика конфиденциальности",
  licenses: "Лицензии",
  feedback: "Обратная связь",
  rate_app: "Оценить приложение",
  share_app: "Поделиться приложением",
  
  // Прогресс
  weight: "Вес",
  height: "Рост",
  bmi: "ИМТ",
  body_fat: "Процент жира",
  muscle_mass: "Мышечная масса",
  measurements: "Измерения",
  waist: "Талия",
  hip: "Бедра",
  chest: "Грудь",
  arm: "Рука",
  leg: "Нога",
  add_weight: "Добавить вес",
  add_measurement: "Добавить измерение",
  weight_history: "История веса",
  measurement_history: "История измерений",
  progress_photos: "Фото прогресса",
  upload_photo: "Загрузить фото",
  take_photo: "Сделать фото",
  front: "Спереди",
  side: "Сбоку",
  back: "Сзади",
  start_date: "Дата начала",
  end_date: "Дата окончания",
  current: "Текущий",
  target: "Целевой",
  lost: "Потеряно",
  gained: "Набрано",
  
  // Аналитика
  nutrition_analysis: "Анализ питания",
  weight_trend: "Тренд веса",
  calorie_trend: "Тренд калорий",
  macros_distribution: "Распределение макронутриентов",
  nutrition_insights: "Инсайты питания",
  activity_analysis: "Анализ активности",
  sleep_analysis: "Анализ сна",
  health_score: "Оценка здоровья",
  daily_average: "Среднее за день",
  weekly_average: "Среднее за неделю",
  monthly_average: "Среднее за месяц",
  yearly_average: "Среднее за год",
  compare: "Сравнить",
  
  // Сообщество
  community: "Сообщество",
  feed: "Лента",
  friends: "Друзья",
  groups: "Группы",
  challenges: "Челленджи",
  events: "События",
  notifications: "Уведомления",
  messages: "Сообщения",
  comments: "Комментарии",
  likes: "Лайки",
  shares: "Поделились",
  followers: "Подписчики",
  following: "Подписки",
  follow: "Подписаться",
  unfollow: "Отписаться",
  like: "Нравится",
  unlike: "Не нравится",
  comment: "Комментировать",
  share: "Поделиться",
  post: "Пост",
  create_post: "Создать пост",
  create_group: "Создать группу",
  join_challenge: "Присоединиться к челленджу",
  leave_challenge: "Покинуть челлендж",
  
  // Премиум
  premium: "Премиум",
  premium_features: "Премиум функции",
  go_premium: "Перейти на премиум",
  restore_purchase: "Восстановить покупку",
  subscription: "Подписка",
  monthly: "Ежемесячно",
  yearly: "Ежегодно",
  lifetime: "Пожизненно",
  free_trial: "Бесплатный период",
  days_left: "Осталось дней",
  cancel_subscription: "Отменить подписку",
  active_subscription: "Активная подписка",
  
  // Дополнительные
  recommended: "Рекомендуемые",
  popular: "Популярные",
  recently_added: "Недавно добавленные",
  most_used: "Часто используемые",
  custom: "Пользовательские",
  default: "По умолчанию",
  apply: "Применить",
  reset: "Сбросить",
  clear: "Очистить",
  select_all: "Выбрать все",
  select: "Выбрать",
  selected: "Выбрано",
  options: "Опции",
  advanced: "Расширенные",
  basic: "Базовые",
  more: "Больше",
  less: "Меньше",
  show_more: "Показать больше",
  show_less: "Показать меньше",
  details: "Детали",
  summary: "Сводка",
  overview: "Обзор",
  today: "Сегодня",
  yesterday: "Вчера",
  this_week: "Эта неделя",
  last_week: "Прошлая неделя",
  this_month: "Этот месяц",
  last_month: "Прошлый месяц",
  this_year: "Этот год",
  last_year: "Прошлый год",
  custom_range: "Произвольный период",
  calendar: "Календарь",
  schedule: "Расписание",
  time: "Время",
  date: "Дата",
  dates: "Даты",
  duration: "Длительность",
  note: "Заметка",
  notes: "Заметки",
  description: "Описание",
  category: "Категория",
  categories: "Категории",
  tag: "Тег",
  tags: "Теги",
  label: "Метка",
  labels: "Метки",
  status: "Статус",
  priority: "Приоритет",
  complete: "Завершено",
  incomplete: "Не завершено",
  active: "Активно",
  inactive: "Неактивно",
  expired: "Истекло",
  upcoming: "Предстоящее",
  
  // Новые ключи для улучшенного функционала
  search_food_or_scan: "Поиск продукта или сканирование",
  scan_barcode: "Сканировать штрих-код",
  voice_search: "Голосовой поиск",
  listening: "Прослушивание...",
  speak_now: "Говорите сейчас",
  voice_search_error: "Ошибка голосового поиска",
  voice_search_not_supported: "Голосовой поиск не поддерживается",
  voice_search_not_supported_description: "Ваш браузер не поддерживает голосовой поиск",
  camera_not_supported: "Камера не поддерживается",
  camera_not_supported_description: "Ваш браузер не поддерживает доступ к камере",
  camera_error: "Ошибка камеры",
  camera_permission_denied: "Доступ к камере запрещен",
  barcode_scanned: "Штрих-код отсканирован",
  product_found: "Найден продукт с кодом: {barcode}",
  duplicate: "Дублировать",
  item_duplicated: "Элемент дублирован",
  item_added_to_meal: "Элемент добавлен в {meal}",
  added_to_favorites: "Добавлено в избранное",
  item_added_to_favorites: "Элемент добавлен в избранное",
  edit_food: "Редактировать продукт",
  edit_food_description: "Изменить информацию о продукте",
  item_deleted: "Элемент удален",
  item_removed_from_meal: "Элемент удален из {meal}",
  body_metrics: "Физические параметры",
  body_metrics_description: "Ваши физические параметры используются для расчета рекомендаций",
  current_weight: "Текущий вес",
  target_weight: "Целевой вес",
  birth_year: "Год рождения",
  gender: "Пол",
  select_gender: "Выберите пол",
  male: "Мужской",
  female: "Женский",
  other: "Другой",
  activity_level: "Уровень активности",
  select_activity_level: "Выберите уровень активности",
  sedentary: "Сидячий образ жизни",
  light_activity: "Легкая активность",
  moderate_activity: "Умеренная активность",
  active: "Активный образ жизни",
  very_active: "Очень активный образ жизни",
  save_changes: "Сохранить изменения",
  profile_updated: "Профиль обновлен",
  profile_update_success: "Ваш профиль успешно обновлен",
  nutrition_analysis_results: "Анализ питания показывает хороший баланс макронутриентов",
  food_added: "Продукт добавлен",
  added_to: "добавлен в",
  cancel: "Отмена",
  chicken_breast: "Куриная грудка",
  buckwheat: "Гречка",
  cottage_cheese: "Творог 5%",
  apple: "Яблоко",
  macronutrients: "Макронутриенты",
  items: "элементов",
  save_list: "Сохранить список",
  meal_planner: "Планировщик питания",
  daily_nutrition: "Дневное питание",
  select_template: "Выбрать шаблон",
};

// Английский перевод
const enTranslations: Translation = {
  // General
  app_name: "CaloriX",
  settings: "Settings",
  save: "Save",
  cancel: "Cancel",
  delete: "Delete",
  edit: "Edit",
  add: "Add",
  search: "Search",
  loading: "Loading...",
  no_results: "No results",
  profile: "Profile",
  logout: "Logout",
  login: "Login",
  register: "Register",
  welcome: "Welcome",
  error: "Error",
  success: "Success",
  warning: "Warning",
  info: "Information",
  close: "Close",
  continue: "Continue",
  back: "Back",
  next: "Next",
  finish: "Finish",
  yes: "Yes",
  no: "No",
  all: "All",
  none: "None",
  or: "or",
  and: "and",
  
  // Authentication
  email: "Email",
  password: "Password",
  confirm_password: "Confirm Password",
  forgot_password: "Forgot password?",
  reset_password: "Reset Password",
  name: "Name",
  surname: "Surname",
  username: "Username",
  remember_me: "Remember me",
  dont_have_account: "Don't have an account?",
  already_have_account: "Already have an account?",
  sign_in: "Sign In",
  sign_up: "Sign Up",
  sign_out: "Sign Out",
  sign_in_with: "Sign in with",
  sign_up_with: "Sign up with",
  
  // Navigation
  home: "Home",
  diary: "Diary",
  analytics: "Analytics",
  planner: "Planner",
  recipes: "Recipes",
  progress: "Progress",
  community: "Community",
  dashboard: "Dashboard",
  my_account: "My Account",
  help: "Help",
  about: "About",
  contact: "Contact",
  
  // Food Diary
  breakfast: "Breakfast",
  lunch: "Lunch",
  dinner: "Dinner",
  snack: "Snack",
  water: "Water",
  add_food: "Add Food",
  add_meal: "Add Meal",
  add_water: "Add Water",
  remove_water: "Remove Water",
  today: "Today",
  yesterday: "Yesterday",
  tomorrow: "Tomorrow",
  calories: "Calories",
  protein: "Protein",
  fat: "Fat",
  carbs: "Carbs",
  fiber: "Fiber",
  sugar: "Sugar",
  sodium: "Sodium",
  cholesterol: "Cholesterol",
  vitamins: "Vitamins",
  minerals: "Minerals",
  water_goal: "Water Goal",
  calorie_goal: "Calorie Goal",
  macros_goal: "Macros Goal",
  remaining: "Remaining",
  consumed: "Consumed",
  burned: "Burned",
  net: "Net",
  total: "Total",
  meal_time: "Meal Time",
  meal_name: "Meal Name",
  food_name: "Food Name",
  food_weight: "Food Weight",
  food_calories: "Calories",
  food_protein: "Protein",
  food_fat: "Fat",
  food_carbs: "Carbs",
  add_to_diary: "Add to Diary",
  nutrition_facts: "Nutrition Facts",
  serving_size: "Serving Size",
  servings: "Servings",
  grams: "grams",
  ml: "ml",
  g: "g",
  kcal: "kcal",
  
  // Planner
  meal_plan: "Meal Plan",
  weekly_plan: "Weekly Plan",
  shopping_list: "Shopping List",
  add_to_plan: "Add to Plan",
  add_to_shopping_list: "Add to Shopping List",
  remove_from_plan: "Remove from Plan",
  create_meal_plan: "Create Meal Plan",
  generate_meal_plan: "Generate Meal Plan",
  customize_plan: "Customize Plan",
  save_plan: "Save Plan",
  monday: "Monday",
  tuesday: "Tuesday",
  wednesday: "Wednesday",
  thursday: "Thursday",
  friday: "Friday",
  saturday: "Saturday",
  sunday: "Sunday",
  week: "Week",
  month: "Month",
  day: "Day",
  
  // Recipes
  recipe: "Recipe",
  recipes: "Recipes",
  ingredients: "Ingredients",
  instructions: "Instructions",
  prep_time: "Prep Time",
  cook_time: "Cook Time",
  total_time: "Total Time",
  servings: "Servings",
  difficulty: "Difficulty",
  easy: "Easy",
  medium: "Medium",
  hard: "Hard",
  cuisine: "Cuisine",
  category: "Category",
  tags: "Tags",
  save_recipe: "Save Recipe",
  add_to_favorites: "Add to Favorites",
  remove_from_favorites: "Remove from Favorites",
  share_recipe: "Share Recipe",
  print_recipe: "Print Recipe",
  search_recipes: "Search Recipes",
  popular_recipes: "Popular Recipes",
  favorite_recipes: "Favorite Recipes",
  my_recipes: "My Recipes",
  breakfast_recipes: "Breakfast Recipes",
  lunch_recipes: "Lunch Recipes",
  dinner_recipes: "Dinner Recipes",
  snack_recipes: "Snack Recipes",
  vegetarian: "Vegetarian",
  vegan: "Vegan",
  gluten_free: "Gluten Free",
  dairy_free: "Dairy Free",
  low_carb: "Low Carb",
  high_protein: "High Protein",
  low_fat: "Low Fat",
  low_calorie: "Low Calorie",
  keto: "Keto",
  paleo: "Paleo",
  quick_meal: "Quick Meal",
  one_pot: "One Pot",
  meal_prep: "Meal Prep",
  family_friendly: "Family Friendly",
  kid_friendly: "Kid Friendly",
  budget_friendly: "Budget Friendly",
  gourmet: "Gourmet",
  seasonal: "Seasonal",
  holidays: "Holidays",
  recipe_calculator: "Recipe Calculator",
  calculate_recipe: "Calculate Recipe",
  add_ingredient: "Add Ingredient",
  amount: "Amount",
  unit: "Unit",
  all_recipes: "All Recipes",
  view_recipe: "View Recipe",
  min: "min",
  recipe_name: "Recipe Name",
  
  // Profile and Settings
  account_settings: "Account Settings",
  personal_info: "Personal Information",
  change_password: "Change Password",
  notification_settings: "Notification Settings",
  privacy_settings: "Privacy Settings",
  app_settings: "App Settings",
  theme: "Theme",
  language: "Language",
  sync_settings: "Sync Settings",
  data_export: "Export Data",
  data_import: "Import Data",
  delete_account: "Delete Account",
  dark_theme: "Dark Theme",
  light_theme: "Light Theme",
  system_theme: "System Theme",
  russian: "Russian",
  english: "English",
  version: "Version",
  terms: "Terms of Service",
  privacy_policy: "Privacy Policy",
  licenses: "Licenses",
  feedback: "Feedback",
  rate_app: "Rate App",
  share_app: "Share App",
  
  // Progress
  weight: "Weight",
  height: "Height",
  bmi: "BMI",
  body_fat: "Body Fat Percentage",
  muscle_mass: "Muscle Mass",
  measurements: "Measurements",
  waist: "Waist",
  hip: "Hip",
  chest: "Chest",
  arm: "Arm",
  leg: "Leg",
  add_weight: "Add Weight",
  add_measurement: "Add Measurement",
  weight_history: "Weight History",
  measurement_history: "Measurement History",
  progress_photos: "Progress Photos",
  upload_photo: "Upload Photo",
  take_photo: "Take Photo",
  front: "Front",
  side: "Side",
  back: "Back",
  start_date: "Start Date",
  end_date: "End Date",
  current: "Current",
  target: "Target",
  lost: "Lost",
  gained: "Gained",
  
  // Analytics
  nutrition_analysis: "Nutrition Analysis",
  weight_trend: "Weight Trend",
  calorie_trend: "Calorie Trend",
  macros_distribution: "Macros Distribution",
  nutrition_insights: "Nutrition Insights",
  activity_analysis: "Activity Analysis",
  sleep_analysis: "Sleep Analysis",
  health_score: "Health Score",
  daily_average: "Daily Average",
  weekly_average: "Weekly Average",
  monthly_average: "Monthly Average",
  yearly_average: "Yearly Average",
  compare: "Compare",
  
  // Community
  community: "Community",
  feed: "Feed",
  friends: "Friends",
  groups: "Groups",
  challenges: "Challenges",
  events: "Events",
  notifications: "Notifications",
  messages: "Messages",
  comments: "Comments",
  likes: "Likes",
  shares: "Shares",
  followers: "Followers",
  following: "Following",
  follow: "Follow",
  unfollow: "Unfollow",
  like: "Like",
  unlike: "Unlike",
  comment: "Comment",
  share: "Share",
  post: "Post",
  create_post: "Create Post",
  create_group: "Create Group",
  join_challenge: "Join Challenge",
  leave_challenge: "Leave Challenge",
  
  // Premium
  premium: "Premium",
  premium_features: "Premium Features",
  go_premium: "Go Premium",
  restore_purchase: "Restore Purchase",
  subscription: "Subscription",
  monthly: "Monthly",
  yearly: "Yearly",
  lifetime: "Lifetime",
  free_trial: "Free Trial",
  days_left: "Days Left",
  cancel_subscription: "Cancel Subscription",
  active_subscription: "Active Subscription",
  
  // Additional
  recommended: "Recommended",
  popular: "Popular",
  recently_added: "Recently Added",
  most_used: "Most Used",
  custom: "Custom",
  default: "Default",
  apply: "Apply",
  reset: "Reset",
  clear: "Clear",
  select_all: "Select All",
  select: "Select",
  selected: "Selected",
  options: "Options",
  advanced: "Advanced",
  basic: "Basic",
  more: "More",
  less: "Less",
  show_more: "Show More",
  show_less: "Show Less",
  details: "Details",
  summary: "Summary",
  overview: "Overview",
  today: "Today",
  yesterday: "Yesterday",
  this_week: "This Week",
  last_week: "Last Week",
  this_month: "This Month",
  last_month: "Last Month",
  this_year: "This Year",
  last_year: "Last Year",
  custom_range: "Custom Range",
  calendar: "Calendar",
  schedule: "Schedule",
  time: "Time",
  date: "Date",
  dates: "Dates",
  duration: "Duration",
  note: "Note",
  notes: "Notes",
  description: "Description",
  category: "Category",
  categories: "Categories",
  tag: "Tag",
  tags: "Tags",
  label: "Label",
  labels: "Labels",
  status: "Status",
  priority: "Priority",
  complete: "Complete",
  incomplete: "Incomplete",
  active: "Active",
  inactive: "Inactive",
  expired: "Expired",
  upcoming: "Upcoming",
  
  // New keys for enhanced functionality
  search_food_or_scan: "Search for food or scan",
  scan_barcode: "Scan Barcode",
  voice_search: "Voice Search",
  listening: "Listening...",
  speak_now: "Speak now",
  voice_search_error: "Voice search error",
  voice_search_not_supported: "Voice search not supported",
  voice_search_not_supported_description: "Your browser does not support voice search",
  camera_not_supported: "Camera not supported",
  camera_not_supported_description: "Your browser does not support camera access",
  camera_error: "Camera error",
  camera_permission_denied: "Camera permission denied",
  barcode_scanned: "Barcode scanned",
  product_found: "Product found with code: {barcode}",
  duplicate: "Duplicate",
  item_duplicated: "Item duplicated",
  item_added_to_meal: "Item added to {meal}",
  added_to_favorites: "Added to favorites",
  item_added_to_favorites: "Item added to favorites",
  edit_food: "Edit food",
  edit_food_description: "Edit food information",
  item_deleted: "Item deleted",
  item_removed_from_meal: "Item removed from {meal}",
  body_metrics: "Body Metrics",
  body_metrics_description: "Your body metrics are used to calculate recommendations",
  current_weight: "Current weight",
  target_weight: "Target weight",
  birth_year: "Birth year",
  gender: "Gender",
  select_gender: "Select gender",
  male: "Male",
  female: "Female",
  other: "Other",
  activity_level: "Activity level",
  select_activity_level: "Select activity level",
  sedentary: "Sedentary",
  light_activity: "Light activity",
  moderate_activity: "Moderate activity",
  active: "Active",
  very_active: "Very active",
  save_changes: "Save changes",
  profile_updated: "Profile updated",
  profile_update_success: "Your profile has been successfully updated",
  nutrition_analysis_results: "Your nutrition analysis shows a good balance of macronutrients",
  food_added: "Food added",
  added_to: "added to",
  chicken_breast: "Chicken breast",
  buckwheat: "Buckwheat",
  cottage_cheese: "Cottage cheese 5%",
  apple: "Apple",
  macronutrients: "Macronutrients",
  items: "items",
  save_list: "Save list",
  meal_planner: "Meal Planner",
  daily_nutrition: "Daily Nutrition",
  select_template: "Select template",
};

// Создаем контекст языка
const LanguageContext = createContext<LanguageContextProps>({
  language: "ru",
  setLanguage: () => {},
  translate: () => "",
  availableLanguages: [
    { code: "ru", label: "Русский" },
    { code: "en", label: "English" }
  ]
});

// Создаем провайдер языка
export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  // Определяем язык браузера по умолчанию (предпочитаем русский)
  const getBrowserLanguage = (): Language => {
    const navigatorLanguage = navigator.language.split("-")[0];
    return navigatorLanguage === "en" ? "en" : "ru";
  };

  // Получаем сохраненный язык из localStorage или используем язык браузера
  const [language, setLanguageState] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem("language");
    return (savedLanguage as Language) || getBrowserLanguage();
  });

  // Доступные языки
  const availableLanguages = [
    { code: "ru" as Language, label: "Русский" },
    { code: "en" as Language, label: "English" }
  ];

  // Устанавливаем язык и сохраняем в localStorage
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  // Получаем перевод по ключу
  const translate = (key: TranslationKey, variables?: Record<string, string | number>): string => {
    const translations = language === "ru" ? ruTranslations : enTranslations;
    let translation = translations[key] || key;
    
    // Если есть переменные, заменяем их в переводе
    if (variables) {
      Object.entries(variables).forEach(([varName, varValue]) => {
        translation = translation.replace(`{${varName}}`, String(varValue));
      });
    }
    
    return translation;
  };

  // Сохраняем язык при изменении
  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, translate, availableLanguages }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Создаем хук для использования контекста языка
export const useLanguage = () => useContext(LanguageContext);
